# Generated by Django 5.0.6 on 2025-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_job_max_salary_alter_job_min_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('manager', 'Manager'), ('director', 'Director')], max_length=50),
        ),
    ]
