# Generated by Django 5.0.6 on 2025-09-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_plan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('selection', models.CharField(max_length=255)),
                ('venue', models.TextField()),
                ('requirements', models.TextField()),
                ('stipend', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(max_length=100)),
                ('perks', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=100)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
