# Generated by Django 5.0.6 on 2025-09-15 08:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_walkindrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkindrive',
            name='id',
            field=models.CharField(default=core.models.generate_custom_WalkInDrive_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
