# Generated by Django 5.0.6 on 2025-09-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_walkindrive_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('walkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.walkindrive')),
            ],
        ),
    ]
