# Generated by Django 5.2.4 on 2025-09-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_examquestion_alter_user_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
    ]
